"""Call conversation state machine. Every accepted transition is stored as a call_event by the voice service."""

CALL_INITIATED = "CALL_INITIATED"
CUSTOMER_ANSWERED = "CUSTOMER_ANSWERED"
IDENTITY_CONFIRMED = "IDENTITY_CONFIRMED"
PAYMENT_PROBLEM_EXPLAINED = "PAYMENT_PROBLEM_EXPLAINED"
INFORMATION_PROVIDED = "INFORMATION_PROVIDED"
RETRY_PAYMENT = "RETRY_PAYMENT"
PAYMENT_RESULT = "PAYMENT_RESULT"
RETRY_LATER = "RETRY_LATER"
DECLINED = "DECLINED"
HUMAN_AGENT = "HUMAN_AGENT"
WRONG_NUMBER = "WRONG_NUMBER"
NO_RESPONSE = "NO_RESPONSE"
ALREADY_PAID = "ALREADY_PAID"
COMPLETED = "COMPLETED"

_DECISIONS = {RETRY_PAYMENT, RETRY_LATER, DECLINED, HUMAN_AGENT, ALREADY_PAID, INFORMATION_PROVIDED}

TRANSITIONS: dict[str, set[str]] = {
    CALL_INITIATED: {CUSTOMER_ANSWERED, NO_RESPONSE, COMPLETED},
    CUSTOMER_ANSWERED: {IDENTITY_CONFIRMED, WRONG_NUMBER, HUMAN_AGENT, COMPLETED},
    IDENTITY_CONFIRMED: {PAYMENT_PROBLEM_EXPLAINED, HUMAN_AGENT, COMPLETED},
    PAYMENT_PROBLEM_EXPLAINED: _DECISIONS | {COMPLETED},
    INFORMATION_PROVIDED: (_DECISIONS - {INFORMATION_PROVIDED}) | {COMPLETED},
    RETRY_PAYMENT: {PAYMENT_RESULT, COMPLETED},
    PAYMENT_RESULT: {RETRY_LATER, HUMAN_AGENT, COMPLETED},
    RETRY_LATER: {COMPLETED}, DECLINED: {COMPLETED}, HUMAN_AGENT: {COMPLETED},
    WRONG_NUMBER: {COMPLETED}, NO_RESPONSE: {COMPLETED}, ALREADY_PAID: {COMPLETED}, COMPLETED: set(),
}

# Outcome recorded on the call when the state is entered
# (the outcome after PAYMENT_RESULT comes from the payment result: RECOVERED / RETRY_FAILED)
STATE_OUTCOME = {
    RETRY_LATER: "RETRY_LATER", DECLINED: "DECLINED", HUMAN_AGENT: "HUMAN_AGENT",
    WRONG_NUMBER: "WRONG_NUMBER", NO_RESPONSE: "NO_RESPONSE", ALREADY_PAID: "ALREADY_PAID",
}


class InvalidTransition(Exception):
    def __init__(self, src: str, dst: str):
        super().__init__(f"invalid transition {src} -> {dst}")
        self.src, self.dst = src, dst


def can_transition(src: str, dst: str) -> bool:
    return dst in TRANSITIONS.get(src, set())


def assert_transition(src: str, dst: str) -> None:
    if not can_transition(src, dst):
        raise InvalidTransition(src, dst)